require 'addressable/uri'
require 'teamsupport/rest/client'

# TODO: require 'teamsupport/asset'
# TODO: require 'teamsupport/asset_ticket'
# TODO: require 'teamsupport/contact'
# TODO: require 'teamsupport/contact_ticket'
require 'teamsupport/customer'
# TODO: require 'teamsupport/customer_contact'
require 'teamsupport/customer_product'
# TODO: require 'teamsupport/customer_ticket'
# TODO: require 'teamsupport/group'
require 'teamsupport/product'
# TODO: require 'teamsupport/product_customer'
# TODO: require 'teamsupport/property'
require 'teamsupport/ticket'
require 'teamsupport/ticket_action'
# TODO: require 'teamsupport/ticket_contact'
# TODO: require 'teamsupport/ticket_customer'
# TODO: require 'teamsupport/user'
# TODO: require 'teamsupport/wiki'
